### ISSUE TITLE
MoveType.slide 这个往上和往下拉，可以消失不见

### ISSUE THREAD

**Issue by longkehuawei** [SDKers/FloatWindow#1]
MoveType.slide 这个往上和往下拉，可以消失不见了，这个怎么解决呀

**Comment by hhhaiai** [comment]
能明确下机型和版本、使用步骤。甚至初步定位

**Comment by badboy-tian** [comment]
把悬浮窗往上拉 或者往下拉 有可能会大半截移出到屏幕外

**Comment by hhhaiai** [comment]
> 下拉 有可能会大半截移出到屏幕外

好的 稍后我测试下。 近期事情比较多  功能验证少。调整结构中。稍等

**Comment by hhhaiai** [comment]
![image](https://user-images.githubusercontent.com/5738285/53062830-1e3a0580-34fd-11e9-9e7f-5b44eac1c6ec.png)

**Comment by hhhaiai** [comment]
这样的是么

**Comment by Ximano** [comment]
> 这样的是么

是悬浮窗可以在屏幕top和bottom推拽到屏幕外，以至于某些时候无法拖拽回屏幕中

**Comment by hhhaiai** [comment]
> > 这样的是么
> 
> 是悬浮窗可以在屏幕top和bottom推拽到屏幕外，以至于某些时候无法拖拽回屏幕中
  
尽快抽空看

**Comment by hhhaiai** [comment]
https://github.com/SDKers/FloatWindow/commit/7bef24bd46b4f2854b4d8fae9e719c79a72076dc  修复。请知
