### ISSUE TITLE
额，编译出错...

### ISSUE THREAD

**Issue by ZORfree** [SDKers/FloatWindow#11]

**Comment by hhhaiai** [comment]
什么情况？  那个平台

**Comment by ZORfree** [comment]
> 什么情况？ 那个平台
windows10
![image](https://user-images.githubusercontent.com/26847215/57205608-54622e00-6ff2-11e9-9678-9ceb3f9d4e0d.png)

**Comment by ZORfree** [comment]
> > 什么情况？ 那个平台
> > windows10
> > ![image](https://user-images.githubusercontent.com/26847215/57205608-54622e00-6ff2-11e9-9678-9ceb3f9d4e0d.png)

最后sample运行成功了，但是依然编译脚本依然编译不了
![image](https://user-images.githubusercontent.com/26847215/57205854-17973680-6ff4-11e9-9d98-c7c4c6e42ecb.png)

**Comment by ZORfree** [comment]
最后按照提示，将relese 改为dexrelese，编译成功，但是没有找到编译后的aar包

**Comment by ZORfree** [comment]
> 什么情况？ 那个平台

ok，最后编译成功了，之前下的是Releases中的1.0.9，不包含编译脚本
编译之后的aar包    https://pan.baidu.com/s/1G5yHOQOLk8u96g-Yw7Dhkg

**Comment by hhhaiai** [comment]
ok
