### ISSUE TITLE
不能用啊

### ISSUE THREAD

**Issue by badboy-tian** [SDKers/FloatWindow#2]
```
Error: Program type already present: android.support.v4.media.MediaBrowserCompat$ItemCallback
```

```
 implementation ("com.github.SDKers:FloatWindow:1.0.9") {
        exclude group: 'com.android.support', module: 'support-v4'
    }
```

这样也不行

**Comment by hhhaiai** [comment]
暂时没有上传 maven center.  您如果需要使用自己编译。或者我给您打包提供RELEASE

**Comment by hhhaiai** [comment]
哪款机型不能用反馈下
 手机型号、特定ROM版本(如MIUI、FLYme)、安卓版本。

**Comment by chengaomin** [comment]
Error: Program type already present: android.support.v4.app.BackStackRecord$Op
一样的问题，求一个正确的打包aar姿势

**Comment by chengaomin** [comment]
补充一句，我用原版的https://github.com/yhaolpz/FloatWindow，在maven { url 'https://jitpack.io' } 的就没有问题

**Comment by chengaomin** [comment]
android-support-v4.jar 引起的，我直接从aar中去掉他，就木有问题了。麻烦处理一下，这个依赖能去掉不

**Comment by badboy-tian** [comment]
谢谢

chengaomin <notifications@github.com> 于2019年2月19日周二 上午9:00写道：

**Comment by badboy-tian** [comment]
随便说一句  如果在app中不显示悬浮窗 当回到桌面后再显示  如何做?

**Comment by hhhaiai** [comment]
> android-support-v4.jar 引起的，我直接从aar中去掉他，就木有问题了。麻烦处理一下，这个依赖能去掉不

好的

**Comment by hhhaiai** [comment]
> 到桌面后再显示 如何做?

这个功能正在优化。 老版本已经修改了代码风格和该版本不一样，未合并。
近期正在抽时间调整几个功能，权限申请，构建组件、展示组件解耦

**Comment by hhhaiai** [comment]
> android-support-v4.jar 引起的，我直接从aar中去掉他，就木有问题了。麻烦处理一下，这个依赖能去掉不

已经去除  
https://github.com/SDKers/FloatWindow/commit/e6e7aae2f09c523698bca704bae0b33be0b9c52a

**Comment by chengaomin** [comment]
验证ok，感谢
