### ISSUE TITLE
隐藏了悬浮窗之后，将APP后台后再打开，悬浮窗自动显示了

### ISSUE THREAD

**Issue by chengaomin** [SDKers/FloatWindow#3]
隐藏了悬浮窗之后，将APP后台后再打开，悬浮窗自动显示了
帮忙看看这个问题

**Comment by hhhaiai** [comment]
https://github.com/SDKers/FloatWindow/commit/6fe1dde32bbfd73cbfbf1dfb5fa4a93e908c74fd
已经修改上库
