### ISSUE TITLE
拖动之后，第一次经常不会触发click

### ISSUE THREAD

**Issue by chengaomin** [SDKers/FloatWindow#4]
https://github.com/yhaolpz/FloatWindow/issues/84

**Comment by hhhaiai** [comment]
你可以使用最新代码看下么。没搭建kotlin项目,没兼容测试

**Comment by hhhaiai** [comment]
如果方便可以日志下， 在 [onActionUp](https://github.com/SDKers/FloatWindow/blob/master/floatwindow/src/com/yhao/floatwindow/impl/IFloatWindowImpl.java#L265 ) 方法中，看走的分支。 在你代码中的View.onClick监听 看下坐标。是否由于坐标为及时更新导致的

**Comment by hhhaiai** [comment]
的确可能存在坐标更新不及时的情况

**Comment by wahyip** [comment]
您和，坐標沒有及時刷新這個情況啥時候可以補上

**Comment by wahyip** [comment]
您好，坐標沒有及時刷新這個情況啥時候可以補上

**Comment by hhhaiai** [comment]
> 您好，坐標沒有及時刷新這個情況啥時候可以補上

已经更新了。

**Comment by chengaomin** [comment]
我测试下来，问题依然存在，拖动后，第一下点击大概率无法出发click事件
