### ISSUE TITLE
从竖屏切换为横屏后，悬浮窗位置没变化

### ISSUE THREAD

**Issue by chengaomin** [SDKers/FloatWindow#6]
1.如果悬浮窗位置在右下角，此时从竖屏到横屏，悬浮窗就不见了
2.切换横屏后，边界不正确，悬浮窗无法对右侧贴边，无法拖动到右侧区域

**Comment by hhhaiai** [comment]
Y轴 导致的出界问题已经修复  https://github.com/SDKers/FloatWindow/commit/7bef24bd46b4f2854b4d8fae9e719c79a72076dc
