### ISSUE TITLE
1.如果悬浮窗位置在右下角，此时从竖屏到横屏，悬浮窗就不见了 2.切换横屏后，边界不正确，悬浮窗无法对右侧贴边，无法拖动到右侧区域

### ISSUE THREAD

**Issue by 767954322** [SDKers/FloatWindow#9]
1.从竖屏到横屏，悬浮窗位置没有按照宽高比展示，导致竖屏如果悬浮窗在下面，切换横屏就显示不出来了。
2.切换横屏后，悬浮窗拖动区域没改变，还是竖屏的区域。

**Comment by hhhaiai** [comment]
这个后面做兼容，最近有点忙

**Comment by wahyip** [comment]
同问~ 目前项目用到了，刚做了pad版，但是横竖屏切换后位置就不对了，尝试调用FloatWindow.destory(tag)的方法，然后再重新初始化一个同样tag的悬浮窗，但是切换屏幕后，就没显示出来了，再切换回来就报
View=android.widget.ImageView{378c298 V.ED..C.. ......I. 0,0-0,0} not attached to window manager
com.yhao.floatwindow.impl.FloatPhone.dismiss(FloatPhone.java:133)

**Comment by hhhaiai** [comment]
横竖屏的 我正在解决。  文档整理完毕上传 附加链接

**Comment by hhhaiai** [comment]
这个已经新版本调整了
